name: HeLP
version: "4.1"
license: "GPL-2.0-or-later"
date: 2026-01-09
description: |
    Hertweck-Luthar-Passi method.

authors:
    - name: Andreas Bächle
      url: mailto:ABachle@gmx.net
    - name: Leo Margolis
      url: https://margollo.github.io

maintainers:
    - name: Andreas Bächle
      url: mailto:ABachle@gmx.net
    - name: Leo Margolis
      url: https://margollo.github.io

GAP: ">=4.13"

needed-pkgs:
    - name: "io"
      version: ">=4.2"
      url: "https://gap-packages.github.io/io"
    - name: "CTblLib"
      version: ">= 1.2.2"
      url: "https://www.math.rwth-aachen.de/~Thomas.Breuer/ctbllib"

suggested-pkgs:
    - name: "4ti2Interface"
      version: ">= 2015.04.29"
      url: "https://homalg-project.github.io/pkg/4ti2Interface"
    - name: "NormalizInterface"
      version: ">= 1.4.1"
      url: "https://gap-packages.github.io/NormalizInterface"

www: https://gap-packages.github.io/HeLP
readme: README
packageinfo: https://gap-packages.github.io/HeLP/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/HeLP/releases/download/v4.1/HeLP-4.1.tar.gz

abstract: |
    <span class="pkgname">HeLP</span> is a package to compute constraints on partial augmentations of torsion units in integral group rings using a method developed by Luthar, Passi and Hertweck.  The package can be employed to verify the Zassenhaus Conjecture, the Prime Graph Question, the Spectrum Problem and the Kimmerle Problem for finite groups, once characters are known. It uses an interface to the software package 4ti2 to solve integral linear inequalities or alternatively Normaliz.

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    HeLP method, torsion units, integral group rings, rational conjugacy, Zassenhaus Conjecture, Prime Graph Question, Spectrum Problem, Kimmerle Problem.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BM26</span>]   <b class='BibAuthor'>Bächle, A. and Margolis, L.</b>,
     <i class='BibTitle'>HeLP, Hertweck-Luthar-Passi method.,
             Version 4.1</i>
     (<span class='BibYear'>2026</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/HeLP">https://gap-packages.github.io/HeLP</a></span>.
    </p>
    

bibtex: |
    @misc{ HeLP,
      author =           {B{\"a}chle, A. and Margolis, L.},
      title =            {{HeLP},
                          {Hertweck\texttt{\symbol{45}}Luthar\texttt{\symbol{45}}Passi
                          method.}, {V}ersion 4.1},
      month =            {Jan},
      year =             {2026},
      note =             {GAP package},
      howpublished =     {\href            {https://gap-packages.github.io/HeLP}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{HeLP}}},
      keywords =         {HeLP  method;  torsion  units;  integral  group rings;
                          rational conjugacy; Zassenhaus Conjecture; Prime Graph
                          Question; Spectrum Problem; Kimmerle Problem},
      printedkey =       {BM26}
    }

